"""Add error type, value and conditions columns to polymer_properties

Revision ID: 03bce2251920
Revises: 2e8c79ae53a6
Create Date: 2023-01-16 11:43:17.786279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pinrex.db.models.polymer import PolymerPropertyErrorTypeEnum

# revision identifiers, used by Alembic.
revision = '03bce2251920'
down_revision = '2e8c79ae53a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PolymerPropertyErrorTypeEnum.create(op.get_bind(), checkfirst=True)
    op.add_column('polymer_properties', sa.Column('error_value', sa.Float(), nullable=True))
    op.add_column('polymer_properties', sa.Column('error_type', postgresql.ENUM('sd', 'sem', 'variance', name='polymerpropertyerrortype'), nullable=True))
    op.add_column('polymer_properties', sa.Column('conditions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polymer_properties', 'conditions')
    op.drop_column('polymer_properties', 'error_type')
    op.drop_column('polymer_properties', 'error_value')
    PolymerPropertyErrorTypeEnum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
