"""Add brettmann lab specific sample information

Revision ID: 05fdd6dc263c
Revises: 1de5bc90ec88
Create Date: 2023-03-13 09:23:01.736266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fdd6dc263c'
down_revision = '1de5bc90ec88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brettmann_lab_polymers', sa.Column('number_average_mw_min', sa.Float(), nullable=True))
    op.add_column('brettmann_lab_polymers', sa.Column('number_average_mw_max', sa.Float(), nullable=True))
    op.add_column('brettmann_lab_polymers', sa.Column('supplier', sa.Text(), nullable=True))
    op.add_column('brettmann_lab_solvents', sa.Column('purity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brettmann_lab_solvents', 'purity')
    op.drop_column('brettmann_lab_polymers', 'supplier')
    op.drop_column('brettmann_lab_polymers', 'number_average_mw_max')
    op.drop_column('brettmann_lab_polymers', 'number_average_mw_min')
    # ### end Alembic commands ###
