"""change single value table to just experiment

Revision ID: 09ba2daae3f6
Revises: 7010c67ebf10
Create Date: 2023-03-15 15:38:45.024411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09ba2daae3f6'
down_revision = '7010c67ebf10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csst_experiment_property_single_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('csst_property_id', sa.Integer(), nullable=False),
    sa.Column('csst_experiment_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['csst_experiment_id'], ['csst_experiments.id'], ),
    sa.ForeignKeyConstraint(['csst_property_id'], ['csst_properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('csst_reactor_property_single_values')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csst_reactor_property_single_values',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('csst_property_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('csst_reactor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['csst_property_id'], ['csst_properties.id'], name='csst_reactor_property_single_values_csst_property_id_fkey'),
    sa.ForeignKeyConstraint(['csst_reactor_id'], ['csst_reactors.id'], name='csst_reactor_property_single_values_csst_reactor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='csst_reactor_property_single_values_pkey')
    )
    op.drop_table('csst_experiment_property_single_values')
    # ### end Alembic commands ###
