"""add experimenter and change name of experimental details to experiment_details

Revision ID: 09c2ead2e349
Revises: d1c750d6181c
Create Date: 2023-03-13 14:57:20.980914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c2ead2e349'
down_revision = 'd1c750d6181c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csst_experiments', sa.Column('experiment_details', sa.Text(), nullable=True))
    op.add_column('csst_experiments', sa.Column('experimenter', sa.Text(), nullable=True))
    op.drop_column('csst_experiments', 'experimental_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csst_experiments', sa.Column('experimental_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('csst_experiments', 'experimenter')
    op.drop_column('csst_experiments', 'experiment_details')
    # ### end Alembic commands ###
