"""add concentration to csst reactor model

Revision ID: 0cc4014916eb
Revises: 9f1d68da1909
Create Date: 2023-03-15 11:07:15.078335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc4014916eb'
down_revision = '9f1d68da1909'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csst_reactors', sa.Column('conc', sa.Float(), nullable=False))
    op.add_column('csst_reactors', sa.Column('conc_unit', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csst_reactors', 'conc_unit')
    op.drop_column('csst_reactors', 'conc')
    # ### end Alembic commands ###
