"""add reaction tables

Revision ID: 2e8c79ae53a6
Revises: 419e19dda06b
Create Date: 2023-01-09 14:24:05.696858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8c79ae53a6'
down_revision = '419e19dda06b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polymerization_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('smarts', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polymerizations',
    sa.Column('polymerization_reaction_id', sa.Integer(), nullable=False),
    sa.Column('monomer_id', sa.Integer(), nullable=False),
    sa.Column('pol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monomer_id'], ['monomers.id'], ),
    sa.ForeignKeyConstraint(['pol_id'], ['polymers.id'], ),
    sa.ForeignKeyConstraint(['polymerization_reaction_id'], ['polymerization_reactions.id'], ),
    sa.PrimaryKeyConstraint('polymerization_reaction_id', 'monomer_id', 'pol_id'),
    sa.UniqueConstraint('polymerization_reaction_id', 'monomer_id', name='unique_monomer_polymerization')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polymerizations')
    op.drop_table('polymerization_reactions')
    # ### end Alembic commands ###
