"""update monomer substructures table

Revision ID: 419e19dda06b
Revises: 
Create Date: 2022-11-21 14:05:11.514211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419e19dda06b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monomer_substructures',
    sa.Column('smarts_id', sa.Integer(), nullable=False),
    sa.Column('monomer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monomer_id'], ['monomers.id'], ),
    sa.ForeignKeyConstraint(['smarts_id'], ['smarts.id'], ),
    sa.PrimaryKeyConstraint('smarts_id', 'monomer_id'),
    sa.UniqueConstraint('smarts_id', 'monomer_id', name='unique_pair')
    )
    op.alter_column('polymer_names', 'pol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('polymer_names', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('polymer_names', 'search_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('solvent_names', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solvent_names', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('polymer_names', 'search_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('polymer_names', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('polymer_names', 'pol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('monomer_substructures')
    # ### end Alembic commands ###
