"""add chembl and zinc15 reference columns to chemical table

Revision ID: 460e5d6f6651
Revises: dccace5ba394
Create Date: 2023-06-13 21:50:57.607341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460e5d6f6651'
down_revision = 'dccace5ba394'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemicals', sa.Column('reference_id', sa.Text(), nullable=True))
    op.add_column('chemicals', sa.Column('reference', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemicals', 'reference')
    op.drop_column('chemicals', 'reference_id')
    # ### end Alembic commands ###
