"""change purity in brettmann solvent cols to percent purity

Revision ID: 4bbab3f4261d
Revises: 05fdd6dc263c
Create Date: 2023-03-13 12:15:10.646073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bbab3f4261d'
down_revision = '05fdd6dc263c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brettmann_lab_solvents', sa.Column('percent_purity', sa.Float(), nullable=True))
    op.drop_column('brettmann_lab_solvents', 'purity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brettmann_lab_solvents', sa.Column('purity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('brettmann_lab_solvents', 'percent_purity')
    # ### end Alembic commands ###
