"""add chemical names

Revision ID: 5c377f2a3595
Revises: 7e51c06cfe8d
Create Date: 2023-04-12 15:20:01.209184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c377f2a3595'
down_revision = '7e51c06cfe8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('search_name', sa.Text(), nullable=False),
    sa.Column('naming_convention', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemicals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical_names')
    # ### end Alembic commands ###
