"""add cas numbers

Revision ID: 7e51c06cfe8d
Revises: ea61a1897f05
Create Date: 2023-04-12 14:51:06.782795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e51c06cfe8d'
down_revision = 'ea61a1897f05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('chemical_smarts_pair', 'chemical_substructures', ['smarts_id', 'chemical_id'])
    op.add_column('chemicals', sa.Column('cas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemicals', 'cas')
    op.drop_constraint('chemical_smarts_pair', 'chemical_substructures', type_='unique')
    # ### end Alembic commands ###
