"""add hash column to temperature program

Revision ID: 9f1d68da1909
Revises: bbaac26fbf49
Create Date: 2023-03-14 09:07:33.487670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1d68da1909'
down_revision = 'bbaac26fbf49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csst_temperature_programs', sa.Column('hash', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csst_temperature_programs', 'hash')
    # ### end Alembic commands ###
