"""change temperature model json components to array of json

Revision ID: bbaac26fbf49
Revises: 09c2ead2e349
Create Date: 2023-03-13 15:03:57.056177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbaac26fbf49'
down_revision = '09c2ead2e349'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csst_temperature_programs', 'solvent_tune')
    op.drop_column('csst_temperature_programs', 'sample_load')
    op.drop_column('csst_temperature_programs', 'experiment')
    op.add_column('csst_temperature_programs', sa.Column('solvent_tune', postgresql.ARRAY(sa.JSON(), dimensions=1), nullable=False))
    op.add_column('csst_temperature_programs', sa.Column('sample_load', postgresql.ARRAY(sa.JSON(), dimensions=1), nullable=False))
    op.add_column('csst_temperature_programs', sa.Column('experiment', postgresql.ARRAY(sa.JSON(), dimensions=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csst_temperature_programs', 'solvent_tune')
    op.drop_column('csst_temperature_programs', 'sample_load')
    op.drop_column('csst_temperature_programs', 'experiment')
    op.add_column('csst_temperature_programs', sa.Column('solvent_tune', sa.JSON(), nullable=False))
    op.add_column('csst_temperature_programs', sa.Column('sample_load', sa.JSON(), nullable=False))
    op.add_column('csst_temperature_programs', sa.Column('experiment', sa.JSON(), nullable=False))
    # ### end Alembic commands ###
