"""remove polyerization and monomer

Revision ID: bfb2bcf593fc
Revises: 460e5d6f6651
Create Date: 2023-07-05 21:10:37.889666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb2bcf593fc'
down_revision = '460e5d6f6651'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polymerizations')
    op.drop_table('polymerization_reactions')
    op.drop_table('monomer_substructures')
    op.drop_table('monomers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polymerizations',
    sa.Column('polymerization_reaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monomer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pol_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monomer_id'], ['monomers.id'], name='polymerizations_monomer_id_fkey'),
    sa.ForeignKeyConstraint(['pol_id'], ['polymers.id'], name='polymerizations_pol_id_fkey'),
    sa.ForeignKeyConstraint(['polymerization_reaction_id'], ['polymerization_reactions.id'], name='polymerizations_polymerization_reaction_id_fkey'),
    sa.PrimaryKeyConstraint('polymerization_reaction_id', 'monomer_id', 'pol_id', name='polymerizations_pkey'),
    sa.UniqueConstraint('polymerization_reaction_id', 'monomer_id', name='unique_monomer_polymerization')
    )
    op.create_table('monomers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('monomers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('smiles', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='monomers_pkey'),
    sa.UniqueConstraint('smiles', name='monomers_smiles_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('monomer_substructures',
    sa.Column('smarts_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monomer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['monomer_id'], ['monomers.id'], name='monomer_substructures_monomer_id_fkey'),
    sa.ForeignKeyConstraint(['smarts_id'], ['smarts.id'], name='monomer_substructures_smarts_id_fkey'),
    sa.UniqueConstraint('smarts_id', 'monomer_id', name='unique_pair')
    )
    op.create_table('polymerization_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('smarts', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='polymerization_reactions_pkey')
    )
    # ### end Alembic commands ###
