"""name uniqueness

Revision ID: d1c750d6181c
Revises: 4bbab3f4261d
Create Date: 2023-03-13 12:34:50.389184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c750d6181c'
down_revision = '4bbab3f4261d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('brettmann_lab_polymers_name_key', 'brettmann_lab_polymers', type_='unique')
    op.create_unique_constraint('unique_pair', 'monomer_substructures', ['smarts_id', 'monomer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_pair', 'monomer_substructures', type_='unique')
    op.create_unique_constraint('brettmann_lab_polymers_name_key', 'brettmann_lab_polymers', ['name'])
    # ### end Alembic commands ###
