"""add reaction starting substructure table

Revision ID: dccace5ba394
Revises: 8686d43dc3e5
Create Date: 2023-04-26 10:34:43.192302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccace5ba394'
down_revision = '8686d43dc3e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction_procedure_starting_substructure',
    sa.Column('reaction_procedure_id', sa.Integer(), nullable=False),
    sa.Column('smarts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reaction_procedure_id'], ['reaction_procedures.id'], ),
    sa.ForeignKeyConstraint(['smarts_id'], ['smarts.id'], ),
    sa.PrimaryKeyConstraint('reaction_procedure_id', 'smarts_id'),
    )
    op.create_unique_constraint('unique_reaction_procedure_starting_substructure', 'reaction_procedure_starting_substructure', ['reaction_procedure_id', 'smarts_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaction_procedure_starting_substructure')
    # ### end Alembic commands ###
