"""add chemical tables

Revision ID: ea61a1897f05
Revises: f3154683157b
Create Date: 2023-04-10 14:23:37.767770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea61a1897f05'
down_revision = 'f3154683157b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('site', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chemicals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('smiles', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('smiles')
    )
    op.create_table('chemical_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('cost_unit', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_unit', sa.Text(), nullable=False),
    sa.Column('usd_cost_per_gram', sa.Float(), nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemicals.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['chemical_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chemical_substructures',
    sa.Column('smarts_id', sa.Integer(), nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemicals.id'], ),
    sa.ForeignKeyConstraint(['smarts_id'], ['smarts.id'], ),
    sa.PrimaryKeyConstraint('smarts_id', 'chemical_id'),
    sa.UniqueConstraint('smarts_id', 'chemical_id', name='chemical_smarts_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical_substructures')
    op.drop_table('chemical_costs')
    op.drop_table('chemicals')
    op.drop_table('chemical_suppliers')
    # ### end Alembic commands ###
