"""add reactor number to CSST reactor

Revision ID: ed1336f24969
Revises: 09ba2daae3f6
Create Date: 2023-03-16 14:25:20.790407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1336f24969'
down_revision = '09ba2daae3f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csst_reactors', sa.Column('reactor_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csst_reactors', 'reactor_number')
    # ### end Alembic commands ###
