"""add models for tox21 data collected from Cooper and Schürer, 'Improving the Utility of the Tox21 Dataset by Deep Metadata Annotations and Constructing Reusable Benchmarked Chemical Reference Signatures', Molecules, vol. 24, no. 8, p. 1604, Apr. 2019, doi: 10.3390/molecules24081604

Revision ID: efcf610d4b33
Revises: 03bce2251920
Create Date: 2023-02-03 11:53:40.409049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efcf610d4b33'
down_revision = '03bce2251920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experimental_cell_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('experimental_cell_clo_id', sa.Text(), nullable=False),
    sa.Column('cell', sa.Text(), nullable=True),
    sa.Column('cell_clo_id', sa.Text(), nullable=True),
    sa.Column('cellosaurus_id', sa.Text(), nullable=True),
    sa.Column('organism', sa.Text(), nullable=True),
    sa.Column('organism_taxon_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experimental_cell_clo_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('uniprot_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uniprot_id')
    )
    op.create_table('tox21_molecules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pubchem_cid', sa.Integer(), nullable=True),
    sa.Column('tox21_sid', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('smiles', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.JSON(), nullable=True),
    sa.Column('cluser', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tox_assays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assay_type', postgresql.ENUM('reporter', 'counter_screen', name='assaytype'), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.Column('pubchem_aid', sa.Integer(), nullable=True),
    sa.Column('tox21_aid', sa.Text(), nullable=True),
    sa.Column('reporter_gene_assay', sa.Text(), nullable=True),
    sa.Column('exp_cell_line_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('target_effect', sa.Text(), nullable=False),
    sa.Column('target_mode_of_action', postgresql.ENUM('agonist', 'antagonist', 'permeabilization', 'inhibition', 'activation', name='targetmodeofaction'), nullable=False),
    sa.Column('kit', sa.Text(), nullable=True),
    sa.Column('physical_detection_method', sa.Text(), nullable=True),
    sa.Column('detection_instrument', sa.Text(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exp_cell_line_id'], ['experimental_cell_lines.id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tox21_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('molecule_id', sa.Integer(), nullable=False),
    sa.Column('assay_id', sa.Integer(), nullable=False),
    sa.Column('activity', postgresql.ENUM('active', 'inactive', 'inconclusive', name='activity'), nullable=False),
    sa.Column('pac50_val', sa.Float(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assay_id'], ['tox_assays.id'], ),
    sa.ForeignKeyConstraint(['molecule_id'], ['tox21_molecules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tox21_data')
    op.drop_table('tox_assays')
    op.drop_table('tox21_molecules')
    op.drop_table('genes')
    op.drop_table('experimental_cell_lines')
    # ### end Alembic commands ###
