"""add processed reactor data to csst file

Revision ID: f3154683157b
Revises: ed1336f24969
Create Date: 2023-03-27 13:05:49.296309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3154683157b'
down_revision = 'ed1336f24969'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csst_reactor_processed_temperature_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('csst_reactor_id', sa.Integer(), nullable=False),
    sa.Column('average_temperature', sa.Float(), nullable=False),
    sa.Column('temperature_range', sa.Float(), nullable=False),
    sa.Column('average_transmission', sa.Float(), nullable=False),
    sa.Column('median_transmission', sa.Float(), nullable=False),
    sa.Column('transmission_std', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['csst_reactor_id'], ['csst_reactors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csst_reactor_processed_temperature_values')
    # ### end Alembic commands ###
